### ISSUE TITLE
foutje in documentatie , date en day, 

### ISSUE THREAD

**Issue by Lab-gek** [Uitgeverij-Instruct/Buienradar#1]
ik heb een mogelijke fout gevonden in de README.MD; hier in word in [lijn 159](https://github.com/Uitgeverij-Instruct/Buienradar/blob/master/README.md?plain=1#L159) aangegeven dat voor het krijgen van de dag, `buienradar.forecast.fiveDays.day(dag)`  gebruikt kan worden, maar in de [demo](https://github.com/Uitgeverij-Instruct/Buienradar/blob/6120e09cb67377efec3b18680c30e8fded4b05b4/examples/demo.html#L388) gebruikt `buienradar.forecast.fiveDays.date` en deze `.date `staat nergens in de README.ME

Ik hoop dat dit genoeg informatie is om het probleem te vinden en op te lossen
als er meer info nodig is hoor ik het graag!

**Comment by WoutervdBrink** [comment]
Dank voor het melden! Gefixt in 0592209.
